-- Type: tpy_cqprog

-- DROP TYPE public.tpy_cqprog;

CREATE TYPE public.tpy_cqprog AS
(
	diahora character varying(15),
	sala character(2),
	paciente character varying(99),
	intervencion character varying(50),
	cirujano character varying(80),
	anestesia character varying(30),
	cama character(6),
	pedido character varying(199),
	codmed character(10),
	cq_numope character(10),
	cq_fecha timestamp without time zone,
	cq_hoinpr timestamp without time zone,
	cq_hofipr timestamp without time zone,
	cq_hoinej timestamp without time zone,
	cq_hofiej timestamp without time zone,
	cq_indrep character(1),
	cq_hoinre timestamp without time zone,
	cq_hofire timestamp without time zone,
	se_codigo character(3),
	cq_codiqx character(6),
	an_tipane character(2),
	cq_cuenta character(10),
	cq_numhis character(10),
	cq_tipcon character(5),
	cq_cama character(6),
	cq_estado character(1),
	cq_indfac character(1),
	edad integer,
	glosa character varying(200),
	npeti character varying(10),
	emer character varying(1),
	ordecq character(1),
	orden_rqx character(1),
	semanas character(10),
	area character(2),
	cq_codiqx2 character(6),
	sd character(1),
	re character(1),
	ho character(1),
	oiqx character(2),
	rqx character(2),
	intervencion2 character varying(50),
	anestesiologo character varying(100),
	adelantado character(1),
	em character(1),
	enfer character(1),
	antibio character(50),
	kg character(2),
	btb character(1),
	reing character(1),
	estancia character(2),
	cq_codiqx3 character(6),
	intervencion3 character varying(50),
	motivo_suspen character(200),
	cmdco numeric(18,0),
	hg character varying(5),
	sexo character(1),
	tiempo integer,
	inf_ope boolean
);
